import { ApiProperty } from '@nestjs/swagger';
import {
  IsBoolean,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
} from 'class-validator';

export class SendMessageDto {
  @ApiProperty({ description: 'The ID of the room to send the message to' })
  @IsNumber()
  @IsNotEmpty()
  roomId: number;

  @ApiProperty({ description: 'The content of the message' })
  @IsString()
  @IsNotEmpty()
  content: string;

  @ApiProperty({
    description: 'Flag indicating if the message was generated by AI',
    required: false,
    default: false,
  })
  @IsBoolean()
  @IsOptional()
  isAiGenerated?: boolean;
}
