version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-space-study-api
    restart: always
    networks:
      - space-study-api
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  space-study-api:
    name: space-study-api
    external: ${SPACE_STUDY_API_NETWORK_EXISTS:-false}

